/* kana.c - Pengu katakana strings and printer.
 * String tables are GENERATED by tools/mkart.py; print_kana
 * is hand written and lives at the bottom.
 */
#include "kana.h"

const u8 s_clear[4] = { K_KU, K_RI, K_A, 0 };
const u8 s_gameover[8] = { K_GE, K_BAR, K_MU, K_O, K_BAR, K_BA, K_BAR, 0 };
const u8 s_hiscore[6] = { K_HA, K_I, K_SU, K_KO, K_A, 0 };
const u8 s_life[4] = { K_RA, K_I, K_FU, 0 };
const u8 s_okinawa[8] = { K_O, K_KI, K_NA, K_WA, K_HNO, K_HYU, K_HME, 0 };
const u8 s_pause[4] = { K_PO, K_BAR, K_ZU, 0 };
const u8 s_stage[5] = { K_SU, K_TE, K_BAR, K_JI, 0 };
const u8 s_start[5] = { K_SU, K_TA, K_BAR, K_TO, 0 };

/* Kana tile IDs are >127, so they cannot travel through a char* the way
 * PrintString() strings do - the sign extension corrupts them.  Same tile
 * write as PrintString, u8 codes instead. */
void print_kana(u8 plane, u8 pal, u8 x, u8 y, const u8 *codes) {
    u16 *screen;
    u16 offset;

    if (plane == SCR_1_PLANE)      screen = SCROLL_PLANE_1;
    else if (plane == SCR_2_PLANE) screen = SCROLL_PLANE_2;
    else return;

    while (*codes) {
        offset = ((u16)y * 32) + x;
        screen[offset] = (u16)(*codes) + ((u16)pal << 9);
        codes++;
        x++;
    }
}
