/* kana.h - Pengu katakana codes and strings.
 * GENERATED by tools/mkart.py - do not hand edit.
 *
 * Kana tile IDs sit above the signed char range, so these are
 * u8 arrays terminated by 0 and printed with print_kana(),
 * never PrintString().
 */
#ifndef KANA_H
#define KANA_H

#include "game.h"

#define K_SU   217
#define K_ZU   218
#define K_TA   219
#define K_BAR  220
#define K_TO   221
#define K_GE   222
#define K_MU   223
#define K_O    224
#define K_BA   225
#define K_PO   226
#define K_HA   227
#define K_I    228
#define K_KO   229
#define K_A    230
#define K_TE   231
#define K_JI   232
#define K_KU   233
#define K_GU   234
#define K_RI   235
#define K_RA   236
#define K_FU   237
#define K_KI   238
#define K_NA   239
#define K_WA   240
#define K_HNO  241
#define K_HYU  242
#define K_HME  243

extern const u8 s_clear[4];
extern const u8 s_gameover[8];
extern const u8 s_hiscore[6];
extern const u8 s_life[4];
extern const u8 s_okinawa[8];
extern const u8 s_pause[4];
extern const u8 s_stage[5];
extern const u8 s_start[5];

void print_kana(u8 plane, u8 pal, u8 x, u8 y, const u8 *codes);

#endif
