/* tiles.h - Pengu tile map.  GENERATED by tools/mkart.py */
#ifndef TILES_H
#define TILES_H

#include "game.h"

#define T_FIELD 144   /* 1: solid ice field */
#define T_ICE   145   /* 4: TL TR BL BR */
#define T_GEM   149   /* 4: unbreakable diamond */
#define T_SHAT  153   /* 8: 2 frames x 4 */
#define T_EDGE  161   /* 8: top bot left right, then TL TR BL BR */
#define T_PENG  169   /* 32: D0 D1 U0 U1 R0 R1 L0 L1 */
#define T_BEE   201   /* 8: 2 frames x 4 */
#define T_ORCA  209   /* 8: 2 frames x 4 */
#define T_KANA  217   /* 27 glyphs */
#define T_TITLE 244   /* 12: PE N GU at 16x16 */
#define T_TRUNK 244   /* 2: banked over the title logo */
#define T_FROND 246   /* 4 */
#define T_PINE  250   /* 1 */
#define T_INTER 217   /* 21: banked over the kana block */
#define T_SEAL  217
#define T_MAW   229
#define T_IGLOO 231
#define T_GUST  235
#define T_SNOW  237

void install_tiles(void);
void install_inter_tiles(void);
void install_tropic_tiles(void);
void install_title_tiles(void);

#endif
